export const PERMISSIONS = {
  READ_DOCUMENT: "READ_DOCUMENT",
  UPLOAD_DOCUMENT: "UPLOAD_DOCUMENT",
  DELETE_DOCUMENT: "DELETE_DOCUMENT",
  MANAGE_USERS: "MANAGE_USERS",
} as const;

export type Permission =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const GROUP_PERMISSIONS = {

  EMPLOYEE: [
    PERMISSIONS.READ_DOCUMENT,
    PERMISSIONS.UPLOAD_DOCUMENT,
  ],

  MANAGER: [
    PERMISSIONS.READ_DOCUMENT,
    PERMISSIONS.UPLOAD_DOCUMENT,
  ],

  HR: [
    PERMISSIONS.READ_DOCUMENT,
    PERMISSIONS.UPLOAD_DOCUMENT,
  ],

  FINANCE: [
    PERMISSIONS.READ_DOCUMENT,
    PERMISSIONS.UPLOAD_DOCUMENT,
  ],

  ADMIN: [
    PERMISSIONS.READ_DOCUMENT,
    PERMISSIONS.UPLOAD_DOCUMENT,
    PERMISSIONS.DELETE_DOCUMENT,
    PERMISSIONS.MANAGE_USERS,
  ],
};